<h3>Kämpfer anlegen</h3> 
<p>Hinterlegen Sie einen neuen Kämpfer um diesen später im Onlinearchiv verwenden zu können.</p>
<hr />
<div ng-controller="FormCtrl">
    <form name="new_fighter" novalidate method="POST" action="<?php echo $this->url('fighter', array('action' => 'new'))  ?>">
        <div class="row">
            <div class="col-xs-3 col-md-3">
                <div class="form-group">
                    <label for="name">Vorname*</label>
                    <input 
                        type="text" 
                        class="form-control"
                        ng-model="firstname"
                        name="firstname" 
                        value="" 
                        placeholder="Vorname"
                        required="">
                    <span ng-show="new_fighter.firstname.$error.required">Dieses Feld ist ein Pflichtfeld.</span>
                </div>
            </div>
            <div class="col-xs-3 col-md-3">
                <div class="form-group" >
                    <label for="name">Nachname*</label>
                    <input 
                        type="text" 
                        class="form-control"
                        ng-model="lastname" 
                        name="lastname" 
                        value="" 
                        placeholder="Nachname"
                        required="">
                    <span ng-show="new_fighter.lastname.$error.required">Dieses Feld ist ein Pflichtfeld.</span>
                    <span ng-if="new_fighter.lastname.$viewValue.length<3">Mindestens 3 Zeichen benötigt.</span>
                </div>
            </div>
         </div>
        <input type="submit" class="btn btn-default" ng-disabled="new_fighter.$invalid || new_fighter.lastname.$viewValue.length<3" value="Kämpfer anlegen">
    </form>
</div>