<div class="row">
    <div class="col-xs-6 col-md-6">
        <div class="form-group" >
            <label>1. Kämpfer</label>
            <input
                disabled=""
                type="text"
                class="form-control"
                <?php if (null != $this->archiveFile->getFighterA()): ?>
                    value="<?php echo $this->archiveFile->getFighterA()->getFullname(); ?>"
                <?php endif; ?>
            >
        </div>
    </div>
    <div class="col-xs-6 col-md-6">
        <div class="form-group" >
            <label>2. Kämpfer</label>
            <input 
                type="text"
                disabled=""
                class="form-control"
                <?php if (null != $this->archiveFile->getFighterB()): ?>
                    value="<?php echo $this->archiveFile->getFighterB()->getFullname() ?>"
                <?php endif; ?>
            >
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-4 col-md-4">
        <div class="form-group" >
        	<label>Date of fight</label>
            <input 
                type="text" 
                name="fight_date"
                required=""
                class="form-control ipm_datepicker" 
                placeholder="Date of fight"
                <?php if (null != $this->archiveFile->getFightDate()): ?>
                    value="<?php echo $this->archiveFile->getFightDate()->format('d.m.Y'); ?>"
                <?php endif; ?>
            >
        </div>
    </div>
    <div class="col-xs-4 col-md-4">
        <div class="form-group" >
        	<label>Location of fight</label>
           <input 
                type="text" 
                name="fight_where"
                required=""
                class="form-control" 
                placeholder="Location of fight"
                <?php if (null != $this->archiveFile->getFightWhere()): ?>
                    value="<?php echo $this->archiveFile->getFightWhere(); ?>"
                <?php endif; ?>
            >
        </div>
    </div>
    <div class="col-xs-4 col-md-4">
        <div class="form-group" >
            <label>Gender</label>
            <select class="form-control" name="gender" required="">
                <option></option>
                <?php foreach (\Application\Form\OptionsConfig::getFormOption('gender') as $optIndex => $optName): ?>
                    <?php if ($optIndex == $this->archiveFile->getGender()): ?>
                        <option value="<?php echo $optIndex; ?>" selected> <?php echo $optName; ?></option>
                    <?php else: ?>
                        <option value="<?php echo $optIndex; ?>"> <?php echo $optName; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-4 col-md-4">
        <div class="form-group" >
            <label>Type of fight</label>
            <select class="form-control" name="fight_type" required="">
                <option></option>
                <?php foreach (\Application\Form\OptionsConfig::getFormOption('fight_type') as $optIndex => $optName): ?>
                    <?php if ($optIndex == $this->archiveFile->getFightType()): ?>
                        <option value="<?php echo $optIndex; ?>" selected> <?php echo $optName; ?></option>
                    <?php else: ?>
                        <option value="<?php echo $optIndex; ?>"> <?php echo $optName; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-xs-4 col-md-4">
        <div class="form-group" >
        	<label>Rounds of fight</label>
             <select class="form-control" name="rounds" required="">
                <option></option>
                <?php foreach (\Application\Form\OptionsConfig::getFormOption('rounds') as $optIndex => $optName): ?>
                    <?php if ($optIndex == $this->archiveFile->getRounds()): ?>
                        <option value="<?php echo $optIndex; ?>" selected> <?php echo $optName; ?></option>
                    <?php else: ?>
                        <option value="<?php echo $optIndex; ?>"> <?php echo $optName; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-xs-4 col-md-4">
        <div class="form-group" >
            <label>Weightclass</label>
            <select class="form-control" name="weight_class" required="">
                <option></option>
                <?php foreach (\Application\Form\OptionsConfig::getFormOption('weight_class') as $optIndex => $optName): ?>
                    <?php if ($optIndex == $this->archiveFile->getWeightClass()): ?>
                        <option value="<?php echo $optIndex; ?>" selected> <?php echo $optName; ?></option>
                    <?php else: ?>
                        <option value="<?php echo $optIndex; ?>"> <?php echo $optName; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-xs-3 col-md-3">
        <div class="form-group" >
            <label>Titlefight</label>
            <select class="form-control" name="fight_title[]" multiple required="">
                <?php foreach (\Application\Form\OptionsConfig::getFormOption('fight_title') as $optIndex => $optName): ?>
                    <?php if (in_array($optName, $this->archiveFile->getFightTitle())): ?>
                        <option value="<?php echo $optIndex; ?>" selected> <?php echo $optName; ?></option>
                    <?php else: ?>
                        <option value="<?php echo $optIndex; ?>"> <?php echo $optName; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
</div> 