<a href="javascript:history.back()">
    <button type="button" class="btn btn-default" aria-label="Left Align">
        Back
    </button>
</a>

<form role="form" action="<?php echo $this->url('changelog', array('action' => 'new')); ?>" method="POST">
    <input type="hidden" name="projectId" value="<?php echo $projectId?>">

  <div class="form-group">
    <input type="text" name="editor" class="form-control" id="exampleInputEmail1" placeholder="Enter editor (aqn/ms)"  >
  </div>
      <div class="form-group">
    <input type="text" name="version" class="form-control" id="exampleInputEmail1" placeholder="Enter Version (like 0.0.1)" >
  </div>
  <div class="form-group">
    <textarea placeholder="Logtext" name="log" class="form-control" rows="3"></textarea>
  </div>

  <button type="submit" class="btn btn-default">Submit</button>
</form>