<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Onlinearchiv - contenthouse GmbH</title>
        
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/all-skins.css')
                        ->prependStylesheet($this->basePath() . '/css/functional.css')
                        ->prependStylesheet($this->basePath() . '/css/playful.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.structure.min.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery-ui.theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/contenthouse.js')
            ->prependFile($this->basePath() . '/js/flowplayer.min.js')
            ->prependFile($this->basePath() . '/js/angular.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body ng-app="myapp">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <ul class="nav navbar-nav navbar-left">
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Archiv-Datei<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                  <li><a href="<?php 
                                    echo $this->url(
                                            'archivefile', 
                                            array('action' => 'newarchivefilestep1')
                                        )  ?>" ng-model="createFileBnt">
                                    Neu
                                </a></li>
                                <li><a href="<?php echo $this->url('archivefiles', array('action' => 'index'))  ?>">Liste</a></li>
                                
                                <li><a href="<?php echo $this->url('archivefiles', array('action' => 'deactivatedfiles'))  ?>">Liste (deaktiviert)</a></li>
                              </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-left">
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sende-Datei<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                  <li>                
                                    <a href="<?php 
                                        echo $this->url(
                                                'sendefile', 
                                                array('action' => 'newsendefilestep')
                                            )  ?>" ng-model="createFileBnt">
                                        Neu
                                    </a></li>
                                <li><a href="<?php echo $this->url('sendefiles', array('action' => 'index'))  ?>">Liste</a></li>
                                <li><a href="<?php echo $this->url('sendefile', array('action' => 'deactivatedfiles'))  ?>">Liste (deaktiviert)</a></li>
                              </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-left">
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Material suchen<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                <li ng-init="createFileBnt=false" ng-click="createFileBnt=true"><a href="<?php echo $this->url('archivefile', array('action' => 'search'))  ?>">Archiv-Datei</a></li>
                                <li ng-init="createFileBnt=false" ng-click="createFileBnt=true"><a href="<?php echo $this->url('sendefile', array('action' => 'search'))  ?>">Sende-Datei</a></li>
                              </ul>
                            </li>
                        </ul>
                        
                        <li><a href="<?php echo $this->url('fighter') ?>">Kämpfer verwalten</a></li>
                    </ul>

</div> 
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <div class="flash_msg">
                <?php echo $this->flashMessenger()->render(); ?>
            </div>
            
            <?php echo $this->content; ?>
            
            <hr />
            <footer>
                <p>&copy; <?php echo date('Y') ?> Contenthouse GmbH</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
