<h3>Deaktivierte Sende-Dateien</h3>
<p>Auf dieser Seite sehen Sie deaktivierte Sende-Dateien.</p>
<hr />
<?php echo $this->partial(
    'partials/application/form/filter/filterforpagination.phtml',
    array(
        'filterAction' => 'sendefiles/deactivatedfiles',
        'route' => 'sendefiles',
        'action' => array('action' => 'deactivatedfiles'),
        'status' => $this->status,
        'limit' => $this->limit
    )); ?>
<hr />
<?php $paging = $this->paginationHelper($this->pagedFiles, $this->page, '/sendefiles/deactivatedfiles', $this->limit, $this->status); ?>
<?php if (!empty($paging)): ?>
    <div class="paging">    
        <?php echo $paging; ?>
    </div>
    <hr />
<?php endif; ?> 

<?php if (isset($this->new) && count($this->new) > 0): ?>
<table ng-hide="createFileBnt" class="table table-striped">
    <thead>
        <tr>
          <th>#</th>
          <th>Dateiname</th>
          <th>Titel</th>
          <th>Status</th>
          <th>Erstellungszeitpunkt</th>
          <th>Aktionen</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->new as $file): ?>
    <tr>
        <td><?php echo $file->getId() ?></td>
        <td><?php echo $file->getName() ?></td>
        <td><?php echo $file->getTitle() ?></td>
        <td><?php echo $file->getFileIndex()->getStatus() ?></td>
        <td><?php echo $file->getCreatedAt()->format('d.m.Y H:i:s') ?></td>
        <td>
        	<a href="<?php 
            echo $this->url(
                'sendefile', 
                array(
                    'action' => 'activate',
                    'id' => $file->getId()
                )
            )  ?>"><div class="btn btn-default">Aktivieren</div></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<?php if (isset($this->notReadyToConvert) && count($this->notReadyToConvert) > 0): ?>
<h4>Not ready to convert</h4>
<table ng-hide="createFileBnt" class="table table-striped">
    <thead>
        <tr>
          <th>#</th>
          <th>Dateiname</th>
          <th>Titel</th>
          <th>Erstellungszeitpunkt</th>
          <th>Aktionen</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->notReadyToConvert as $file): ?>
    <tr>
        <td><?php echo $file->getId() ?></td>
        <td><?php echo $file->getName() ?></td>
        <td><?php echo $file->getTitle() ?></td>
        <td><?php echo $file->getCreatedAt()->format('d.m.Y H:i:s') ?></td>
        <td>
        	<a href="<?php 
            echo $this->url(
                'sendefile', 
                array(
                    'action' => 'activate',
                    'id' => $file->getId()
                )
            )  ?>"><div class="btn btn-default">Aktivieren</div></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>


<?php if (isset($this->readyToConvert) && count($this->readyToConvert) > 0): ?>
<h4>Not ready to convert</h4>
<table ng-hide="createFileBnt" class="table table-striped">
    <thead>
        <tr>
          <th>#</th>
          <th>Dateiname</th>
          <th>Titel</th>
          <th>Erstellungszeitpunkt</th>
          <th>Aktionen</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->readyToConvert as $file): ?>
    <tr>
        <td><?php echo $file->getId() ?></td>
        <td><?php echo $file->getName() ?></td>
        <td><?php echo $file->getTitle() ?></td>
        <td><?php echo $file->getCreatedAt()->format('d.m.Y H:i:s') ?></td>
        <td>
        	<a href="<?php 
            echo $this->url(
                'sendefile', 
                array(
                    'action' => 'activate',
                    'id' => $file->getId()
                )
            )  ?>"><div class="btn btn-default">Aktivieren</div></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<?php if (isset($this->convertInProgress) && count($this->convertInProgress) > 0): ?>
<h4>Not ready to convert</h4>
<table ng-hide="createFileBnt" class="table table-striped">
    <thead>
        <tr>
          <th>#</th>
          <th>Dateiname</th>
          <th>Titel</th>
          <th>Erstellungszeitpunkt</th>
          <th>Aktionen</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->convertInProgress as $file): ?>
    <tr>
        <td><?php echo $file->getId() ?></td>
        <td><?php echo $file->getName() ?></td>
        <td><?php echo $file->getTitle() ?></td>
        <td><?php echo $file->getCreatedAt()->format('d.m.Y H:i:s') ?></td>
        <td>
            <a href="<?php 
            echo $this->url(
                'sendefile', 
                array(
                    'action' => 'activate',
                    'id' => $file->getId()
                )
            )  ?>"><div class="btn btn-default">Aktivieren</div></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<?php if (isset($this->finished) && count($this->finished) > 0): ?>
<h4>Not ready to convert</h4>
<table ng-hide="createFileBnt" class="table table-striped">
    <thead>
        <tr>
          <th>#</th>
          <th>Dateiname</th>
          <th>Titel</th>
          <th>Erstellungszeitpunkt</th>
          <th>Aktionen</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->finished as $file): ?>
    <tr>
        <td><?php echo $file->getId() ?></td>
        <td><?php echo $file->getName() ?></td>
        <td><?php echo $file->getTitle() ?></td>
        <td><?php echo $file->getCreatedAt()->format('d.m.Y H:i:s') ?></td>
        <td>
            <a href="<?php 
            echo $this->url(
                'sendefile', 
                array(
                    'action' => 'activate',
                    'id' => $file->getId()
                )
            )  ?>"><div class="btn btn-default">Aktivieren</div></a>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>