<h4>Datei</h4>
<div class="row">
    <div class="col-xs-3 col-md-3">
        <div class="form-group">
            <label for="name">Dateiname</label>
            <input type="text" class="form-control" name="name" placeholder="Dateiname">
        </div>
    </div>
    <div class="col-xs-3 col-md-3">
        <div class="form-group">
            <label for="name">Storage</label>
            <input type="text" class="form-control" name="storage" placeholder="Storage">
        </div>
    </div>
</div>