<h4>Allgemeines</h4>
<div class="row">
    <div class="col-xs-3 col-md-3">
        <div class="form-group">
            <label>Quelle</label>
            <select class="form-control" name="source">
                <option></option>
                <?php foreach (\Application\Form\OptionsConfig::getFormOption('source') as $optIndex => $optName): ?>
                    <option value="<?php echo $optIndex; ?>"> <?php echo $optName; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="col-xs-3 col-md-3">
        <div class="form-group">
            <label for="path">Tape</label>
            <input type="text" name="path" class="form-control" placeholder="Tape">
        </div>
    </div>
    <div class="col-xs-3 col-md-3">
        <div class="form-group" >
            <label for="name">Status</label>
            <select class="form-control" name="status">
                <option></option>
                <?php foreach (\Application\Form\OptionsConfig::getFormOption('status') as $optIndex => $optName): ?>
                    <option value="<?php echo $optIndex; ?>"> <?php echo $optName; ?></option>
                <?php endforeach; ?>
                <option value="Finished">Finished</option>
            </select>
        </div>
    </div>
</div>