<div class="btn btn-default"><a href="<?php echo $this->url('archivefile', array('action' => 'newarchivefile'))  ?>">neu Archiv-Date erstellen</a></div>


<?php if (isset($this->archiveFiles) && count($this->archiveFiles) > 0): ?>
    <table class="table table-striped">
        <thead>
            <tr>
              <th>#</th>
              <th>File Name</th>
              <th>Status</th>
              <th>Created At</th>
              <th></th>
            </tr>
        </thead>
    <?php foreach ($this->archiveFiles as $archiveFile): ?>
        <tr>
            <th><?php echo $archiveFile->getId() ?></th>
            <th><?php echo $archiveFile->getName() ?></th>
            <th><?php echo $archiveFile->getStatus() ?></th>
            <th><?php echo $archiveFile->getCreatedAt()->format('d.m.Y') ?> At</th>
            <th>
                <div class="btn btn-default"><a href="<?php 
                    echo $this->url(
                        'archivefile', 
                        array(
                            'action' => 'editarchivefile',
                            'id' => $archiveFile->getId()
                        )
                    )  ?>">Edit</a></div>
            </th>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif; ?>
