<h3>Objekt anlegen</h3>
<p>Von hier aus können neue Objekte im Onlinearchiv angelegt werden.</p>
<hr />
<h4>Welches Objekt möchten Sie erstellen? (Schritt 1 von 2)</h4>
<div class="row">
    <div class="col-xs-6 col-md-6">
        <div class="row">
            <div class="col-xs-6 col-md-6">
                <a href="<?php 
                    echo $this->url(
                            'archivefile', 
                            array('action' => 'newarchivefilestep1')
                        )  ?>" ng-model="createFileBnt">
                    <div class="btn btn-default">Archiv-Datei</div>
                </a>
                <a href="<?php 
                    echo $this->url(
                            'sendefile', 
                            array('action' => 'newsendefilestep1')
                        )  ?>" ng-model="createFileBnt">
                    <div class="btn btn-default">Sende-Datei</div>
                </a>
            </div>
        </div> 
    </div>  
</div>